[package]
name = "sapvi"
version = "0.1.0"
authors = ["narodnik <x@x.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "sapvi"

[dependencies]
ff = "0.8"
group = "0.8"
bellman = { version = "0.8", default-features = false, features = ["groth16"] }
bls12_381 = "0.3.1"
jubjub = "0.5.1"

zcash_primitives = { git = "https://github.com/zcash/librustzcash" }
zcash_proofs = { git = "https://github.com/zcash/librustzcash" }
#zcash_proofs = { git = "https://github.com/narodnik/librustzcash" }
#bench-utils = { git = "https://github.com/scipr-lab/zexe", features = ["print-trace"]}
rand = "0.7.3"
rand_core = "0.5.1"
sha2 = "0.9.1"
rand_xorshift = "0.2"
blake2s_simd = "0.5"
bitvec = "0.18"
bimap = "0.5.2"

hex = "0.4.2"

simplelog = "0.7.4"
clap = "3.0.0-beta.1"
failure = "0.1.8"
failure_derive = "0.1.8"

regex = "1"

lazy_static = "1.4.0"
itertools = "0.8.0"
fnv = "1.0.6"

[[bin]]
name = "basic"
path = "src/old/basic_minimal.rs"

[[bin]]
name = "mimc"
path = "src/bin/mimc.rs"

[[bin]]
name = "zkvm"
path = "src/bin/zkvm.rs"

[[bin]]
name = "mint"
path = "src/bin/mint.rs"

[[bin]]
name = "jubjub"
path = "src/bin/jubjub.rs"

[[bin]]
name = "lisp"
path = "lisp/lisp.rs"
